### PR TITLE
Re-adjust everything

### PR DESCRIPTION
**Pull request by sewnie**
Sorry if my scripting will be incomprehensible. It is purely my own style of things. One thing I did take into consideration is your weird function line breaks however.

I scripted this on a system that Isn't Arch. So _please_ test this and let me know of any problems. 

I added a version flag as well. 

I won't tell you much other than the following:
+ Plethora of commands are repeated. I suggest you use one function for it (eg. print, create, remove as in my modified kbuilder, and the fetch function.)
+ Random function line breaks and spaces(?). generally functions should look like `function()`, as for the `{` That's personal preference.
+ Too many ifs. Sometimes you have to check basic things and take them into account, Personally I get irritated by them because it reminds me of Yandere Dev code lol.
+ Know what you are dealing with. I won't say much about this but if you are  scripting, always take full advantage of the shell's features and whatever is used in your script.

### CODE REVIEW

**Comment by sewnie** [comment]
Also, as for the `build install` arguments, that won't be possible. I would love to suggest you use the bash built in argument parser (getopts), or change the case statement values to `*build*` and `*install*` Though that might not work.

**Comment by sewnie** [comment]
I also suggest a command handler. For printing if the command failed and outputting its logs somewhere maybe.

**Comment by AnnikaV9** [comment]
Wow, thanks a lot for putting so much effort :D
I will test the changes as soon as possible.

**Comment by sewnie** [comment]
Also, if this script DID have problems, set the shebang to
```
#!/usr/bin/env -S bash -x
```
or
```
#!/bin/bash -x
```
This adds `-x` to the flags of bash for debugging mode.
Alternatively, 
```
set -x
```

**Pull request merged**
